src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Scheb\TwoFactorBundle\Model\Totp\TotpConfigurationInterface;
use Scheb\TwoFactorBundle\Model\Totp\TwoFactorInterface;
use Scheb\TwoFactorBundle\Model\Totp\TotpConfiguration;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;


/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface, TwoFactorInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("user:read")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Groups("user:read")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups("user:read")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    private $plainPassword;

    /**
     * @ORM\OneToMany(targetEntity=Question::class, mappedBy="owner", orphanRemoval=true)
     */
    private $questions;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $totpSecret;


    public function __construct()
    {
        $this->roles = ['ROLE_USER'];
        $this->questions = new ArrayCollection();
        $this->isVerified = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * This method can be removed in Symfony 6.0 - is not needed for apps that do not check user passwords.
     *
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }


    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }


    public function setPlainPassword(string $plainPassword): self
    {
        $this->plainPassword = $plainPassword;
        return $this;
    }


    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getIsVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;
        return $this;
    }

    public function getTotpSecret(): ?string
    {
        return $this->totpSecret;
    }
    public function setTotpSecret(?string $totpSecret): self
    {
        $this->totpSecret = $totpSecret;
        return $this;
    }

    /**
     * This method can be removed in Symfony 6.0 - is not needed for apps that do not check user passwords.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
         $this->plainPassword = null;
    }

    /**
     * @Groups("user:read")
     */
    public function getAvatarUri(int $size = 32): string
    {
        return 'https://ui-avatars.com/api/?' . http_build_query([
            'name' => $this->getDisplayName(),
            'size' => $size,
            'random' => 'random',
        ]);
    }

    /**
     * @Groups("user:read")
     */
    public function getDisplayName(): string
    {
        return $this->getFirstName() ?: $this->getEmail();
    }

    /**
     * @return Collection<int, Question>
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions[] = $question;
            $question->setOwner($this);
        }
        return $this;
    }

    public function removeQuestion(Question $question): self
    {
        if ($this->questions->removeElement($question)) {
            // set the owning side to null (unless already changed)
            if ($question->getOwner() === $this) {
                $question->setOwner(null);
            }
        }
        return $this;
    }

    // 2-factor authentication methods
    public function isTotpAuthenticationEnabled(): bool
    {
        return $this->totpSecret ? true : false;
    }

    public function getTotpAuthenticationUsername(): string
    {
        return $this->getUserIdentifier();
    }

    public function getTotpAuthenticationConfiguration(): ?TotpConfigurationInterface
    {
        return new TotpConfiguration($this->totpSecret, TotpConfiguration::ALGORITHM_SHA1, 30, 6);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Spartan&display=swap">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
            {{ encore_entry_link_tags('app') }}
        {% endblock %}
        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
    {% for flash in app.flashes('success') %}
        <div class="alert alert-success">{{ flash }}</div>
    {% endfor %}
    {% for flash in app.flashes('error') %}
        <div class="alert alert-danger">{{ flash }}</div>
    {% endfor %}
    {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
        {{ stimulus_controller('user-api', {
            url: path('app_user_api_me')
        }) }}
    {% endif %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light px-1">
            {{ is_granted('ROLE_PREVIOUS_ADMIN') ? 'style="background-color: red !important"' }}
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ path('app_homepage') }}">
                    <p class="pl-2 d-inline font-weight-bold" style="color: #444;">
                        Cauldron Overflow</p>
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-collapsable" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbar-collapsable">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('app_popular_answers') }}">Answers</a>
                        </li>
                        {% if is_granted('ROLE_ADMIN') %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ path('admin_dashboard') }}">Admin</a>
                            </li>
                        {% endif %}
                    </ul>
                    {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
                        <div class="d-flex">
                            {#<a href="{{ path('app_logout') }}" class="btn btn-outline-danger">Logout</a>#}
                            <div class="dropdown">
                                <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                    {#<img src="https://ui-avatars.com/api/?name={{ app.user.firstName|url_encode }}&size=32&background=random"
                                         alt="{{ app.user.firstName }} Avatar">#}
                                    {# {{ app.user.userIdentifier }}#}
                                    <img src="{{ app.user.avatarUri }}" alt="{{ app.user.displayName }} Avatar" >
                                </button>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="user-dropdown">
                                    {#<li><a class="dropdown-item" href="{{ path('app_profile', {'username': app.user.userIdentifier}) }}">Profile</a></li>#}
                                    <li>
                                        <a class="dropdown-item" href="{{ path('app_2fa_enable') }}">Enable 2fa</a>
                                    </li>
                                    {% if is_granted('IS_IMPERSONATOR') %}
                                        <li><a class="dropdown-item" href="{{ impersonation_exit_path(path('app_homepage') ) }}">Exit impersonation</a></li>
                                    {% endif %}
                                    <li>
                                        <a class="dropdown-item" href="{{ path('app_logout') }}">Logout</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    {% else %}
                        <div class="d-flex">
                            <a href="{{ path('app_login') }}" class="nav-link text-black-50">Login</a>
                            <a href="{{ path('app_register') }}" class="btn btn-dark">Sign up</a>
                        </div>
                    {% endif %}
                    {#<a class="nav-link text-black-50" href="{{ path('app_login') }}">Log In</a>
                    <a href="#" class="btn btn-dark">Sign up</a>#}
                </div>
            </div>
        </nav>
        {% block body %}{% endblock %}
        <footer class="mt-5 p-3 text-center">
            Made with <i style="color: red;" class="fa fa-heart"></i> by the guys and gals at <a style="color: #444; text-decoration: underline;" href="https://symfonycasts.com">SymfonyCasts</a>
        </footer>
    </body>
</html>